#!/bin/bash
set -euo pipefail

echo "Publishing gh_pages..."
ember github-pages:commit --message \"chore: Deploy gh-pages from commit $(git rev-parse HEAD)\"
git push
git checkout -
git push
git checkout master

echo "All done!"
